#pragma once
// Builds without Windows report file errors with the Windows error codes the import
// errors already explain (import_error.cpp): errno is translated once, here.
#ifdef _WIN32
#include <windows.h>
#else
#include <cerrno>
#include <cstdint>
constexpr uint32_t ERROR_SUCCESS=0,ERROR_INVALID_FUNCTION=1,ERROR_FILE_NOT_FOUND=2,ERROR_PATH_NOT_FOUND=3,ERROR_ACCESS_DENIED=5,
 ERROR_INVALID_DRIVE=15,ERROR_NO_MORE_FILES=18,ERROR_WRITE_PROTECT=19,ERROR_NOT_READY=21,ERROR_CRC=23,ERROR_SHARING_VIOLATION=32,
 ERROR_LOCK_VIOLATION=33,ERROR_HANDLE_DISK_FULL=39,ERROR_NOT_SUPPORTED=50,ERROR_BAD_NETPATH=53,ERROR_DEV_NOT_EXIST=55,
 ERROR_UNEXP_NET_ERR=59,ERROR_NETNAME_DELETED=64,ERROR_FILE_EXISTS=80,ERROR_INVALID_PARAMETER=87,ERROR_DISK_FULL=112,
 ERROR_INSUFFICIENT_BUFFER=122,ERROR_INVALID_NAME=123,ERROR_BAD_PATHNAME=161,ERROR_ALREADY_EXISTS=183,
 ERROR_FILENAME_EXCED_RANGE=206,ERROR_VIRUS_INFECTED=225,ERROR_VIRUS_DELETED=226,ERROR_DIRECTORY=267,ERROR_IO_PENDING=997,
 ERROR_IO_DEVICE=1117,ERROR_FILE_CORRUPT=1392,ERROR_DISK_CORRUPT=1393;
// The Windows error code closest to an errno value.
inline uint32_t windowsError(int error){
 switch(error){
  case 0:return ERROR_SUCCESS;
  case ENOENT:return ERROR_FILE_NOT_FOUND;
  case ENOTDIR:return ERROR_PATH_NOT_FOUND;
  case EACCES:case EPERM:return ERROR_ACCESS_DENIED;
  case EROFS:return ERROR_WRITE_PROTECT;
  case EBUSY:case ETXTBSY:return ERROR_SHARING_VIOLATION;
  case ENOSPC:case EDQUOT:return ERROR_DISK_FULL;
  case EIO:return ERROR_IO_DEVICE;
  case ENXIO:case ENODEV:return ERROR_DEV_NOT_EXIST;
  case ENAMETOOLONG:return ERROR_FILENAME_EXCED_RANGE;
  case EISDIR:return ERROR_DIRECTORY;
  case EEXIST:return ERROR_FILE_EXISTS;
  case EINVAL:case EILSEQ:return ERROR_INVALID_NAME;
  case ENOTSUP:return ERROR_NOT_SUPPORTED;
  case ESTALE:case ENOTCONN:case EHOSTDOWN:case ENETDOWN:return ERROR_UNEXP_NET_ERR;
  default:return ERROR_INVALID_FUNCTION;
 }
}
#endif
