"""Write the code page tables of the Linux builds from Python's codecs.

Windows decodes model text with MultiByteToWideChar; the Linux builds use these tables:
  native/codepage_tables.hpp  code pages 932, 936 (GBK), 949 and 950, for codepages.cpp
  native/cp932_table.h        CP932 both ways, for nanoem's text factory (nanoem_unicode.c)

    python scripts/codepage-tables.py           rewrite both files
    python scripts/codepage-tables.py --check   fail when they differ from the codecs
"""
import argparse, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CODECS = (('cp932', 'cp932'), ('gbk', 'cp936'), ('cp949', 'cp949'), ('cp950', 'cp950'))


def character(codec, data):
    try:
        text = data.decode(codec)
    except UnicodeDecodeError:
        return 0
    return ord(text) if len(text) == 1 and ord(text) <= 0xFFFF else 0


def rows(values):
    return '\n'.join('{' + ','.join(str(v) for v in row) + '},' for row in values)


def codepage_tables():
    out = ["// Generated by scripts/codepage-tables.py from Python's codecs (cp932, gbk, cp949, cp950); do not edit.",
           '// Double-byte characters of the East Asian Windows code pages, for builds without',
           '// MultiByteToWideChar: lead bytes 0x81-0xFE (126 rows), trail bytes 0x40-0xFE (191',
           '// columns); 0 marks an unassigned pair.',
           '#pragma once', '#include <cstdint>', 'namespace mmd::codepage_tables {']
    for codec, name in CODECS:
        table = [[character(codec, bytes((lead, trail))) for trail in range(0x40, 0xFF)] for lead in range(0x81, 0xFF)]
        count = sum(1 for row in table for v in row if v)
        out += [f'// {codec}: {count} characters', f'inline constexpr uint16_t {name}[126][191]={{', rows(table), '};']
    out.append('}')
    return '\n'.join(out) + '\n'


def cp932_table():
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
    decode = [[character('cp932', bytes((lead, trail))) for trail in range(0x40, 0xFD)] for lead in leads]
    encode = []
    for unit in range(0x80, 0x10000):
        if 0xD800 <= unit <= 0xDFFF:
            continue
        try:
            data = chr(unit).encode('cp932')
        except UnicodeEncodeError:
            continue
        encode.append((unit, data[0] if len(data) == 1 else data[0] << 8 | data[1]))
    lines = [','.join('{%d,%d}' % pair for pair in encode[i:i + 16]) + ',' for i in range(0, len(encode), 16)]
    out = ["/* Generated by scripts/codepage-tables.py from Python's cp932 codec (Microsoft's CP932 mapping); do not edit. */",
           '#pragma once', '#include <stdint.h>',
           '/* Double-byte decoding: lead bytes 0x81-0x9F, 0xE0-0xFC (60 rows), trail bytes 0x40-0xFC; 0 = unassigned. */',
           'static const uint16_t mmdhl_cp932_decode[60][189]={', rows(decode), '};',
           '/* Encoding: Unicode code unit -> CP932 bytes (one byte when below 0x100), ascending by code unit. */',
           f'static const uint16_t mmdhl_cp932_encode[{len(encode)}][2]={{', '\n'.join(lines), '};']
    return '\n'.join(out) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = {ROOT / 'native/codepage_tables.hpp': codepage_tables(), ROOT / 'native/cp932_table.h': cp932_table()}
    stale = [path for path, text in files.items() if not path.is_file() or path.read_text(encoding='utf8') != text]
    if args.check:
        for path in stale:
            print(f'{path.relative_to(ROOT)} differs from the codecs')
        return 1 if stale else 0
    for path, text in files.items():
        path.write_text(text, encoding='utf8', newline='\n')
    print('Wrote ' + ', '.join(str(path.relative_to(ROOT)) for path in files))
    return 0


if __name__ == '__main__':
    sys.exit(main())
