"""Refresh factual skeleton/limit/name data from the user's SCMI project.

No Blender import or execution of SCMI scripts is needed. The generated header
is self-contained, so installed hot importers do not depend on the corpus.
"""
import argparse, ast, hashlib, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[1]

def literal(path, name):
    tree = ast.parse(path.read_text(encoding='utf-8-sig'))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            return ast.literal_eval(node.value)
    raise ValueError(name)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--scmi', type=pathlib.Path, required=True)
    p.add_argument('--reference', type=pathlib.Path, required=True)
    a = p.parse_args()
    collision = a.scmi / 'tools/blender_sort_collision.py'
    limits = literal(collision, 'DEFAULT_PHYSICS_QC_SETTINGS')
    lines = a.reference.read_text(encoding='utf-8-sig').splitlines()
    start, end = lines.index('nodes') + 1, lines.index('end')
    nodes = {}
    for line in lines[start:end]:
        m = re.fullmatch(r'\s*(\d+)\s+"([^"]+)"\s+(-?\d+)\s*', line)
        if m:
            i, name, parent = m.groups()
            nodes[int(i)] = {'name': name, 'parent': int(parent)}
    start = lines.index('skeleton') + 2
    for line in lines[start:]:
        if line == 'end': break
        values = line.split()
        if len(values) == 7:
            nodes[int(values[0])]['position'] = list(map(float, values[1:4]))
            nodes[int(values[0])]['angles'] = list(map(float, values[4:7]))
    data = {'version': 1, 'referenceSha256': hashlib.sha256(a.reference.read_bytes()).hexdigest(),
            'bones': list(nodes.values()), 'limits': limits,
            'flexNames': json.loads((a.scmi/'tools/flex_name_dictionary.json').read_text(encoding='utf-8-sig'))['mapping']}
    encoded = json.dumps(data, ensure_ascii=True, separators=(',', ':'))
    out = ROOT/'native/scmi_data.hpp'
    out.write_text('// Generated by scripts/sync-scmi-data.py. SCMI skeleton conventions, joint settings and morph names.\n'
                   '#pragma once\nnamespace mmd { inline constexpr const char* ScmiData =\n'+
                   '\n'.join('R"SCMI('+encoded[i:i+12000]+')SCMI"' for i in range(0,len(encoded),12000))+'; }\n', encoding='utf-8')
    print('Wrote', out, 'with', len(nodes), 'reference bones and', len(data['flexNames']), 'flex aliases')

if __name__ == '__main__': main()
