"""Characters in other formats through the worker CLI (CTest character_import_worker).

Runs mmdhl_worker --request the way the game does and checks the status.json fields
the bone window and the library read: the probe job (kind bone_map), a bone map the
converter rejects (errorCode, errorDetails, stageCode, source), an accepted one (asset,
manifest conversion block, fit), a COLLADA file, a VRM saved as .glb and a PMX taking
the old path, older Lua's plain request, and the OBJ/BLEND refusals; that a model's
buffers and textures come only from its own folders and never from a place file access
never reads (the worker's denylist); and that a damaged list of source paths (characters'
and static props') is kept and reported, not written over. The models are generated by
the C++ tests; nothing needs the game, a GPU, the network or user files.

Usage: test-character-import.py <mmdhl_worker> <mmdhl_character_import_tests> <mmdhl_vrm_tests>
"""
import json
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VB = 'ValveBiped.Bip01_'
checks = 0


def check(ok, name):
    global checks
    if not ok:
        raise SystemExit(f'FAIL {name}')
    checks += 1
    print(f'PASS {name}')


def main(worker, tests, vrm_tests):
    work = Path(tempfile.mkdtemp(prefix='mmdhl-character-worker-'))
    try:
        fixtures = work / 'fixtures'
        subprocess.run([str(tests), '--write-fixtures', str(fixtures)], check=True, capture_output=True, timeout=120)
        subprocess.run([str(vrm_tests), '--write-fixture', str(fixtures / 'avatar.glb')], check=True, capture_output=True, timeout=120)
        jobs = iter(range(1000))

        def request(source, options):
            job = work / f'job{next(jobs)}'
            job.mkdir()
            (job / 'request.json').write_text(json.dumps({'source': str(source), 'cache': str(work / 'cache'), 'options': options}), encoding='utf-8')
            run = subprocess.run([str(worker), '--request', str(job / 'request.json')], capture_output=True, timeout=300)
            return run.returncode, json.loads((job / 'status.json').read_text(encoding='utf-8'))

        def probe(source):
            code, status = request(source, {'kind': 'character_probe'})
            p = status.get('probe') or {}
            ok = (code == 0 and status.get('state') == 'complete' and status.get('kind') == 'bone_map' and status.get('source') == str(source)
                  and status.get('filename') == source.name and p.get('version') == 1 and len(p.get('sourceSha256', '')) == 64
                  and len(p['skeleton']['bones']) > 15 and p['auto']['humanoid'] is True)
            return ok, p

        def automatic(p):
            bones = p['skeleton']['bones']
            name = lambda g: bones[g['bone']]['name'] if g['bone'] >= 0 else ''
            return {'kind': 'character', 'requestVersion': 1, 'boneMap': {k: name(g) for k, g in p['auto']['slots'].items()},
                    'eyes': {side: name(g) for side, g in p['auto']['eyes'].items()}}

        mixamo = fixtures / 'mixamo.glb'
        ok, p = probe(mixamo)
        check(ok and p['format'] == 'glb', 'probe: complete with kind bone_map, the probe and its source file')
        convert = automatic(p)

        rejected = json.loads(json.dumps(convert))
        rejected['boneMap'][VB + 'L_Hand'] = 'NoSuchBone'
        code, s = request(mixamo, rejected)
        d = s.get('errorDetails') or {}
        check(code != 0 and s['state'] == 'failed' and s.get('errorCode') == 'character.bone_map' and d.get('reason') == 'missing' and d.get('slot') == VB + 'L_Hand'
              and s.get('stageCode') == 'convert_character' and s.get('kind') == 'character' and s.get('source') == str(mixamo) and s.get('filename') == 'mixamo.glb',
              'convert: a rejected bone map reports its code, reason, part, stage and source')

        code, s = request(mixamo, convert)
        info = s.get('info') or {}
        check(code == 0 and s['state'] == 'complete' and len(s.get('asset', '')) == 64 and info.get('conversion', {}).get('boneMap', {}).get(VB + 'Pelvis') == 0
              and s.get('fit') == {'ok': True} and 'fit' not in info and s.get('source') == str(mixamo), 'convert: complete with the asset, the conversion block and the fit')
        asset = s['asset']
        code, s = request(mixamo, convert)
        check(s.get('asset') == asset, 'convert: the same file and request give the same asset')

        dae = fixtures / 'humanoid.dae'
        ok, p = probe(dae)
        check(ok and p['format'] == 'dae' and abs(p['height']['meters'] - 1.68) < .03, 'dae: the COLLADA humanoid is probed')
        code, s = request(dae, automatic(p))
        check(code == 0 and s['state'] == 'complete' and s.get('fit') == {'ok': True} and s['info']['conversion']['format'] == 'dae', 'dae: it converts, imports and fits')

        # Older Lua sends no bone map: certain automatic maps import, unsure ones need the window.
        code, s = request(mixamo, {})
        check(code == 0 and s['state'] == 'complete' and 'conversion' in s['info'], 'legacy: a plain request maps a certain skeleton automatically')
        code, s = request(fixtures / 'numbered.glb', {})
        check(s['state'] == 'failed' and s.get('errorCode') == 'character.needs_mapping', 'legacy: an unsure skeleton needs the bone window')

        # Characters the old path reads: a VRM saved as .glb and a PMX.
        code, s = request(fixtures / 'avatar.glb', {'kind': 'character_probe'})
        check(code == 0 and s['state'] == 'complete' and s.get('kind') is None and 'vrm' in s.get('info', {}) and 'fit' in s, 'probe: a VRM saved as .glb imports as before')
        pmx = ROOT / 'tests/fixtures/cloth21.pmx'
        code, s = request(pmx, {'kind': 'character_probe'})
        check(code == 0 and s['state'] == 'complete' and s.get('kind') is None and len(s.get('asset', '')) == 64 and 'fit' in s, 'probe: a PMX imports as before')

        obj = work / 'triangle.obj'
        obj.write_text('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n', encoding='ascii')
        code, s = request(obj, {'kind': 'character_probe'})
        check(s['state'] == 'failed' and s.get('errorCode') == 'character.format' and (s.get('errorDetails') or {}).get('format') == 'obj', 'refused: OBJ files have no skeleton')
        blend = work / 'scene.blend'
        blend.write_bytes(b'BLENDER-v300')
        code, s = request(blend, {'kind': 'character_probe'})
        check(s['state'] == 'failed' and s.get('errorCode') == 'character.blend', 'refused: Blender files')

        # A model names only files in its own folders: a buffer that climbs out fails the
        # import, and a texture file access never reads (wallet.dat anywhere) stays missing.
        glb = mixamo.read_bytes()
        length = struct.unpack_from('<I', glb, 12)[0]
        document = json.loads(glb[20:20 + length])
        size = struct.unpack_from('<I', glb, 20 + length)[0]
        binary = glb[28 + length:28 + length + size]
        model, outside = work / 'deps' / 'model', work / 'deps' / 'outside'
        model.mkdir(parents=True)
        outside.mkdir()
        (model / 'mixamo.bin').write_bytes(binary)
        (outside / 'far.bin').write_bytes(binary)  # Assimp also tries a missing buffer's name beside the model
        rows = (b'\x00' + b'\xff\x80\x40\xff' * 2) * 2  # a 2 x 2 RGBA image
        chunk = lambda kind, data: struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))
        png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', 2, 2, 8, 6, 0, 0, 0)) + chunk(b'IDAT', zlib.compress(rows)) + chunk(b'IEND', b'')
        (model / 'wallet.dat').write_bytes(png)
        (model / 'skin.png').write_bytes(png)

        def gltf(name, buffer, picture=None):
            d = json.loads(json.dumps(document))
            d['buffers'][0]['uri'] = buffer
            if picture:
                d['images'][0] = {'uri': picture}
            (model / name).write_text(json.dumps(d), encoding='utf-8')
            return model / name

        code, s = request(gltf('escape.gltf', '../outside/far.bin'), {'kind': 'character_probe'})
        check(s['state'] == 'failed' and s.get('errorCode') == 'character.parse', 'dependencies: a buffer outside the model\'s folder is never read')
        for picture, readable in (('skin.png', True), ('wallet.dat', False)):
            ok, p = probe(gltf('texture.gltf', 'mixamo.bin', picture))
            code, s = request(model / 'texture.gltf', automatic(p))
            missing = any('Missing texture: wallet.dat' in w for w in (s.get('info') or {}).get('warnings', []))
            check(ok and s['state'] == 'complete' and missing != readable,
                  'dependencies: a texture beside the model is read' if readable else 'dependencies: a never-readable file (wallet.dat) is not read as a texture')

        # A damaged list of source paths is set aside under a new name and reported, never written over.
        tetra = work / 'tetra.obj'
        tetra.write_text('v 0 0 0\nv 1 0 0\nv 0 1 0\nv 0 0 1\nf 1 3 2\nf 1 2 4\nf 1 4 3\nf 2 3 4\n', encoding='ascii')
        for label, source, options, registry in (('character', mixamo, convert, work / 'cache' / 'sources.local.json'),
                                                 ('static prop', tetra, {'kind': 'static'}, work / 'cache' / 'static' / 'sources.local.json')):
            code, s = request(source, options)
            check(code == 0 and s['state'] == 'complete' and 'registryBackup' not in s, f'registry: a readable {label} list is not reported')
            registry.write_text('{"cut off": ', encoding='utf-8')
            code, s = request(source, options)
            kept = registry.parent / str(s.get('registryBackup'))
            check(code == 0 and s['state'] == 'complete' and str(s.get('registryBackup', '')).startswith('sources.local.json.damaged-') and kept.is_file()
                  and kept.read_text(encoding='utf-8') == '{"cut off": ' and list(json.loads(registry.read_text(encoding='utf-8'))) == [s['asset']],
                  f'registry: a damaged {label} list is kept beside the new one and reported')
    finally:
        shutil.rmtree(work, ignore_errors=True)
    print(f'{checks} worker checks passed')


if __name__ == '__main__':
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    main(*(Path(a) for a in sys.argv[1:4]))
